import type {
  ActivityItem,
  ClauseAnalysis,
  Contract,
  DashboardMetrics,
  TopClauseFlag,
  User,
} from "@/types/contract";
import {
  cloudClauses,
  consultingClauses,
  dpaClauses,
  msaDocumentSections,
  ndaClauses,
  partnershipClauses,
  saasClauses,
  saasDocumentSections,
} from "./mock-contracts-text";

// Anchor "now" so demo data is stable across renders within a session.
const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000);
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000);

export const currentUser: User = {
  id: "usr_001",
  name: "Priya Menon",
  email: "priya@clauseium.com",
  role: "admin",
  initials: "PM",
  avatarColor: "bg-brand-500",
};

const teamMembers = {
  priya: { name: "Priya Menon", initials: "PM", color: "bg-brand-500" },
  arjun: { name: "Arjun Subramanian", initials: "AS", color: "bg-counsel-500" },
  nidhi: { name: "Nidhi Kapoor", initials: "NK", color: "bg-risk-info" },
  ravi: { name: "Ravi Shankar", initials: "RS", color: "bg-risk-low" },
  divya: { name: "Divya Iyer", initials: "DI", color: "bg-risk-med" },
  karan: { name: "Karan Malhotra", initials: "KM", color: "bg-brand-600" },
};

// Full clause set for Contract #1 (Vendor MSA — TechCo × Clauseium Pvt Ltd)
const msaClauses: ClauseAnalysis[] = [
  // HIGH RISK (4)
  {
    id: "cl_001",
    clauseNumber: "14.2",
    category: "limitation_of_liability",
    title: "Limitation of Liability",
    originalText:
      "Notwithstanding anything to the contrary, the aggregate liability of the Service Provider arising out of or in connection with this Agreement shall not exceed an amount equal to three (3) months of fees paid by the Customer in the twelve (12) months preceding the event giving rise to the claim.",
    riskLevel: "high",
    summary:
      "Liability cap of 3 months of fees is well below industry standard for Indian SaaS MSAs.",
    reasoning:
      "Standard market practice in India for vendor MSAs is a liability cap equal to 12 months of fees, with carve-outs for IP infringement, data breach, and gross negligence. A 3-month cap exposes the Customer to disproportionate risk in the event of a material breach. This is significantly below the 50th percentile of comparable agreements in our benchmark corpus.",
    suggestedRedline:
      "Notwithstanding anything to the contrary, the aggregate liability of the Service Provider arising out of or in connection with this Agreement shall not exceed an amount equal to twelve (12) months of fees paid by the Customer in the twelve (12) months preceding the event giving rise to the claim; provided that the foregoing limitation shall not apply to (a) claims arising from infringement of intellectual property rights, (b) breach of confidentiality obligations, (c) breach of data protection obligations under the Digital Personal Data Protection Act, 2023, or (d) gross negligence or wilful misconduct.",
    citations: [
      {
        id: "cit_001",
        text: "§73, Indian Contract Act, 1872",
        source: "Indian Contract Act, 1872",
        section: "73",
        status: "verified",
      },
      {
        id: "cit_002",
        text: "§13, DPDP Act, 2023",
        source: "Digital Personal Data Protection Act, 2023",
        section: "13",
        status: "verified",
      },
    ],
    confidence: 96,
    isFromPlaybook: true,
    marketPosition: "below",
  },
  {
    id: "cl_002",
    clauseNumber: "8.3",
    category: "data_protection_dpdp",
    title: "Data Protection",
    originalText:
      "The Service Provider shall implement reasonable security practices to protect Personal Data processed under this Agreement and shall comply with applicable data protection laws.",
    riskLevel: "high",
    summary:
      "Missing Data Principal rights, breach notification timeline, and DPA annexure required under DPDP Act 2023.",
    reasoning:
      "The clause is materially deficient under the Digital Personal Data Protection Act, 2023. It does not specify (i) the rights of Data Principals under §11–§14, (ii) the breach notification timeline (72 hours under DPDP Rules 2025), (iii) sub-processor obligations, or (iv) cross-border transfer restrictions. A separate Data Processing Agreement (DPA) must be annexed.",
    suggestedRedline:
      "The Service Provider shall, in its capacity as a Data Processor: (a) process Personal Data only on documented instructions from the Customer; (b) implement and maintain the security safeguards prescribed under §8(5) of the DPDP Act, 2023 and the rules thereunder; (c) notify the Customer of any Personal Data breach within twenty-four (24) hours of discovery; (d) assist the Customer in fulfilling Data Principal rights under §11–§14; and (e) execute the Data Processing Agreement annexed hereto as Schedule D.",
    citations: [
      {
        id: "cit_003",
        text: "§8(1), DPDP Act, 2023",
        source: "Digital Personal Data Protection Act, 2023",
        section: "8(1)",
        status: "verified",
      },
      {
        id: "cit_004",
        text: "§11, DPDP Act, 2023",
        source: "Digital Personal Data Protection Act, 2023",
        section: "11",
        status: "verified",
      },
    ],
    confidence: 98,
    isFromPlaybook: true,
    marketPosition: "below",
  },
  {
    id: "cl_003",
    clauseNumber: "12.1",
    category: "indemnification",
    title: "Indemnification",
    originalText:
      "The Customer shall indemnify, defend and hold harmless the Service Provider from and against any and all third-party claims, damages, losses and expenses arising out of or in connection with the Customer's use of the Services.",
    riskLevel: "high",
    summary:
      "One-sided indemnification favouring vendor. No reciprocal IP or breach indemnity from Service Provider.",
    reasoning:
      "Standard Indian commercial practice requires mutual indemnification, with the Service Provider indemnifying the Customer for: (a) third-party IP infringement claims arising from the Services, (b) breach of data protection obligations, and (c) breach of representations and warranties. The current drafting places the entire indemnification burden on the Customer.",
    suggestedRedline:
      "Each Party (the 'Indemnifying Party') shall indemnify, defend and hold harmless the other Party from and against any third-party claims arising out of: (a) the Indemnifying Party's breach of this Agreement; (b) gross negligence or wilful misconduct of the Indemnifying Party; and (c) in the case of the Service Provider, any claim that the Services infringe a third party's intellectual property rights.",
    citations: [
      {
        id: "cit_005",
        text: "§73, Indian Contract Act, 1872",
        source: "Indian Contract Act, 1872",
        section: "73",
        status: "verified",
      },
      {
        id: "cit_006",
        text: "§74, Indian Contract Act, 1872",
        source: "Indian Contract Act, 1872",
        section: "74",
        status: "verified",
      },
    ],
    confidence: 94,
    isFromPlaybook: true,
    marketPosition: "below",
  },
  {
    id: "cl_004",
    clauseNumber: "16.4",
    category: "termination",
    title: "Auto-renewal",
    originalText:
      "This Agreement shall automatically renew for successive periods of one (1) year unless either Party provides written notice of non-renewal at least ninety (90) days prior to the expiration of the then-current term.",
    riskLevel: "high",
    summary:
      "Silent auto-renewal with 90-day exit window is non-standard for Indian SaaS contracts.",
    reasoning:
      "Typical Indian B2B SaaS contracts allow a 30-day opt-out window for auto-renewal. A 90-day window combined with silent renewal (no affirmative consent required) creates a procurement trap and is increasingly disfavoured under emerging consumer protection guidance applied to B2B contexts.",
    suggestedRedline:
      "This Agreement shall renew for successive periods of one (1) year only upon the Customer's written affirmative consent provided not less than thirty (30) days prior to the expiration of the then-current term. Absent such written consent, this Agreement shall expire at the end of the then-current term.",
    citations: [
      {
        id: "cit_007",
        text: "§2(46), Consumer Protection Act, 2019",
        source: "Consumer Protection Act, 2019",
        section: "2(46)",
        status: "partially_verified",
      },
    ],
    confidence: 88,
    isFromPlaybook: true,
    marketPosition: "below",
  },

  // MEDIUM RISK (7)
  {
    id: "cl_005",
    clauseNumber: "21.1",
    category: "governing_law",
    title: "Governing Law",
    originalText:
      "This Agreement shall be governed by and construed in accordance with the laws of India, without regard to its conflict of laws principles.",
    riskLevel: "medium",
    summary: "Governing law is India, but jurisdiction clause references Singapore — internal inconsistency.",
    reasoning:
      "While the governing law is correctly stated as India, §21.2 (Jurisdiction) references the Singapore International Arbitration Centre (SIAC) as the exclusive forum. This creates ambiguity around enforcement of interim relief and the scope of Indian court jurisdiction under §9 of the Arbitration and Conciliation Act, 1996.",
    suggestedRedline:
      "This Agreement shall be governed by and construed in accordance with the substantive laws of India, without regard to its conflict of laws principles. The seat of arbitration shall be Mumbai, India, and the courts at Mumbai shall have exclusive jurisdiction in respect of interim relief.",
    citations: [
      {
        id: "cit_008",
        text: "§9, Arbitration and Conciliation Act, 1996",
        source: "Arbitration and Conciliation Act, 1996",
        section: "9",
        status: "verified",
      },
    ],
    confidence: 92,
    isFromPlaybook: true,
    marketPosition: "at",
  },
  {
    id: "cl_006",
    clauseNumber: "21.2",
    category: "arbitration",
    title: "Arbitration",
    originalText:
      "Any dispute arising out of this Agreement shall be referred to and finally resolved by arbitration administered by the Singapore International Arbitration Centre (SIAC) in accordance with the SIAC Rules then in force.",
    riskLevel: "medium",
    summary: "SIAC seat for an India-governing-law contract — reconsider domestic seat.",
    reasoning:
      "A foreign-seated arbitration with Indian governing law is permissible but introduces enforcement complexity and higher cost. Given the parties' Indian nexus, a domestic seat (Mumbai or New Delhi) under the Arbitration and Conciliation Act, 1996, with administered arbitration via MCIA or DIAC, is preferable.",
    citations: [
      {
        id: "cit_009",
        text: "§20, Arbitration and Conciliation Act, 1996",
        source: "Arbitration and Conciliation Act, 1996",
        section: "20",
        status: "verified",
      },
    ],
    confidence: 85,
    isFromPlaybook: true,
    marketPosition: "at",
  },
  {
    id: "cl_007",
    clauseNumber: "9.1",
    category: "ip_assignment",
    title: "IP Assignment",
    originalText:
      "All intellectual property rights in deliverables created by the Service Provider in the course of performing the Services shall be assigned to the Customer upon payment in full.",
    riskLevel: "medium",
    summary: "Scope of IP assignment unclear — does not exclude pre-existing or background IP.",
    reasoning:
      "The clause does not carve out the Service Provider's pre-existing intellectual property or generally applicable tools, frameworks, and know-how. This is unusual and could inadvertently transfer the Service Provider's underlying platform IP.",
    suggestedRedline:
      "All intellectual property rights in deliverables specifically created for the Customer ('Foreground IP') shall be assigned to the Customer upon payment in full. The Service Provider's pre-existing intellectual property, generally applicable tools, methodologies and know-how ('Background IP') shall remain the property of the Service Provider, with a perpetual, royalty-free licence granted to the Customer to the extent necessary to use the Foreground IP.",
    citations: [
      {
        id: "cit_010",
        text: "§17, Copyright Act, 1957",
        source: "Copyright Act, 1957",
        section: "17",
        status: "verified",
      },
    ],
    confidence: 90,
    isFromPlaybook: true,
    marketPosition: "below",
  },
  {
    id: "cl_008",
    clauseNumber: "11.3",
    category: "non_compete",
    title: "Non-compete",
    originalText:
      "For a period of twenty-four (24) months following termination, the Customer shall not engage any competitor of the Service Provider for similar services within India.",
    riskLevel: "medium",
    summary: "Geographic scope (all India) and duration (24 months) likely unenforceable post-termination.",
    reasoning:
      "Under §27 of the Indian Contract Act, 1872, post-termination non-compete restraints are generally void as restraint of trade. Even where narrow restraints have been upheld, courts typically require reasonable scope. A pan-India, 24-month restraint is unlikely to be enforceable.",
    citations: [
      {
        id: "cit_011",
        text: "§27, Indian Contract Act, 1872",
        source: "Indian Contract Act, 1872",
        section: "27",
        status: "verified",
      },
    ],
    confidence: 95,
    isFromPlaybook: true,
    marketPosition: "below",
  },
  {
    id: "cl_009",
    clauseNumber: "5.1",
    category: "payment_terms",
    title: "Payment Terms",
    originalText:
      "Customer shall pay all undisputed invoices within ninety (90) days of the invoice date.",
    riskLevel: "medium",
    summary: "Net-90 payment terms; market standard for Indian B2B SaaS is Net-30 to Net-45.",
    reasoning:
      "Net-90 is materially longer than the Indian B2B SaaS market standard (Net-30 to Net-45). The MSME Development Act, 2006 also imposes a 45-day cap for payments to registered MSMEs. Confirm whether the counterparty is MSME-registered.",
    suggestedRedline:
      "Customer shall pay all undisputed invoices within forty-five (45) days of the invoice date. Where the Service Provider is registered under the MSME Development Act, 2006, payment shall be made within the statutory period prescribed thereunder.",
    citations: [
      {
        id: "cit_012",
        text: "§15, MSMED Act, 2006",
        source: "Micro, Small and Medium Enterprises Development Act, 2006",
        section: "15",
        status: "verified",
      },
    ],
    confidence: 89,
    isFromPlaybook: true,
    marketPosition: "below",
  },
  {
    id: "cl_010",
    clauseNumber: "17.2",
    category: "force_majeure",
    title: "Force Majeure",
    originalText:
      "Neither Party shall be liable for delay or failure to perform due to causes beyond its reasonable control, including acts of God, war, and natural disasters.",
    riskLevel: "medium",
    summary: "Force majeure list does not include pandemics, cyberattacks, or government action.",
    reasoning:
      "Post-2020 Indian commercial drafting commonly includes pandemics, epidemics, public health emergencies, cyberattacks, and acts of governmental authority within the force majeure definition. Their absence may create gaps in coverage.",
    citations: [
      {
        id: "cit_013",
        text: "§56, Indian Contract Act, 1872",
        source: "Indian Contract Act, 1872",
        section: "56",
        status: "verified",
      },
    ],
    confidence: 87,
    isFromPlaybook: false,
    marketPosition: "below",
  },
  {
    id: "cl_011",
    clauseNumber: "13.1",
    category: "insurance",
    title: "Insurance",
    originalText:
      "The Service Provider shall maintain commercial general liability insurance of not less than INR 5,00,00,000.",
    riskLevel: "medium",
    summary: "Insurance covers CGL only; missing cyber liability and professional indemnity cover.",
    reasoning:
      "For a vendor handling Personal Data and providing professional services, the insurance schedule should include: (i) Cyber Liability (minimum ₹10 crore), (ii) Professional Indemnity (minimum ₹5 crore), and (iii) Errors & Omissions cover. CGL alone is insufficient.",
    citations: [],
    confidence: 84,
    isFromPlaybook: true,
    marketPosition: "below",
  },

  // STANDARD (24) — abbreviated, all "low/standard"
  ...Array.from({ length: 24 }, (_, i): ClauseAnalysis => {
    const titles = [
      "Confidentiality",
      "Term",
      "Notices",
      "Entire Agreement",
      "Amendment",
      "Severability",
      "Waiver",
      "Assignment",
      "Counterparts",
      "Survival",
      "Headings",
      "Interpretation",
      "Definitions",
      "Acceptance",
      "Service Levels",
      "Acceptable Use",
      "Suspension",
      "Cooperation",
      "Audit",
      "Records",
      "Subcontracting",
      "Publicity",
      "Independent Contractor",
      "No Third-Party Beneficiaries",
    ];
    return {
      id: `cl_std_${i}`,
      clauseNumber: `${i + 1}.0`,
      category: "confidentiality",
      title: titles[i],
      originalText: `${titles[i]} clause as drafted is consistent with market-standard Indian commercial practice and our internal playbook.`,
      riskLevel: "standard",
      summary: "Market-standard drafting; no changes required.",
      reasoning: "This clause aligns with the firm's playbook and the 50th-percentile drafting in our benchmark corpus.",
      citations: [],
      confidence: 95,
      isFromPlaybook: true,
      marketPosition: "at",
    };
  }),

  // MISSING (2)
  {
    id: "cl_miss_001",
    clauseNumber: "—",
    category: "representations_warranties",
    title: "Anti-Bribery & Anti-Corruption",
    originalText: "(Not present in this Agreement.)",
    riskLevel: "missing",
    summary: "No anti-bribery clause referencing the Prevention of Corruption Act, 1988.",
    reasoning:
      "Standard Indian commercial contracts include explicit ABAC representations referencing the Prevention of Corruption Act, 1988 (as amended in 2018) and, where applicable, the FCPA / UK Bribery Act. Absence of an ABAC clause is a material gap for vendor agreements.",
    suggestedRedline:
      "Each Party represents and warrants that, in connection with this Agreement, neither it nor any person acting on its behalf has offered, given, or received any bribe, kickback or other improper benefit, and shall comply with the Prevention of Corruption Act, 1988 and all other applicable anti-bribery and anti-corruption laws.",
    citations: [
      {
        id: "cit_014",
        text: "Prevention of Corruption Act, 1988",
        source: "Prevention of Corruption Act, 1988",
        section: "—",
        status: "verified",
      },
    ],
    confidence: 91,
    isFromPlaybook: true,
    marketPosition: "below",
  },
  {
    id: "cl_miss_002",
    clauseNumber: "—",
    category: "representations_warranties",
    title: "POSH Compliance",
    originalText: "(Not present in this Agreement.)",
    riskLevel: "missing",
    summary: "No POSH (Sexual Harassment of Women at Workplace Act, 2013) compliance representation.",
    reasoning:
      "Where vendor personnel work at the Customer's premises or interact with Customer employees, market practice is to include a POSH compliance representation requiring the vendor to have a constituted Internal Committee and a written POSH policy.",
    suggestedRedline:
      "The Service Provider represents that it has constituted an Internal Committee under §4 of the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013, and shall ensure that all personnel deployed under this Agreement comply with the Customer's POSH policy.",
    citations: [
      {
        id: "cit_015",
        text: "§4, POSH Act, 2013",
        source: "Sexual Harassment of Women at Workplace Act, 2013",
        section: "4",
        status: "verified",
      },
    ],
    confidence: 93,
    isFromPlaybook: true,
    marketPosition: "below",
  },
];

export const contracts: Contract[] = [
  {
    id: "ctr_001",
    title: "Vendor MSA — TechCo × Clauseium Pvt Ltd",
    counterparty: "Acme Cloud Services Pvt Ltd",
    contractType: "msa",
    jurisdiction: "Mumbai",
    governingLaw: "Laws of India",
    status: "reviewed",
    riskSummary: {
      high: 4,
      medium: 7,
      low: 12,
      standard: 12,
      missing: 2,
      overallScore: 62,
      escalationRecommended: true,
      escalationReason: "Liability cap and DPDP gaps require partner sign-off",
    },
    totalClauses: 47,
    reviewedClauses: 47,
    assignedTo: "Priya Menon",
    uploadedBy: "Arjun Subramanian",
    uploadedAt: daysAgo(3),
    lastUpdated: hoursAgo(2),
    version: 2,
    fileSize: "4.7 MB",
    pageCount: 32,
    tags: ["DPDP", "Cross-border", "SaaS"],
    clauses: msaClauses,
    documentSections: msaDocumentSections,
  },
  {
    id: "ctr_002",
    title: "SaaS Subscription Agreement",
    counterparty: "Razorpay Software Pvt Ltd",
    contractType: "saas_agreement",
    jurisdiction: "Bengaluru",
    governingLaw: "Laws of India",
    status: "needs_attention",
    riskSummary: {
      high: 2,
      medium: 5,
      low: 7,
      standard: 8,
      missing: 0,
      overallScore: 71,
      escalationRecommended: false,
    },
    totalClauses: 22,
    reviewedClauses: 22,
    assignedTo: "Nidhi Kapoor",
    uploadedBy: "Priya Menon",
    uploadedAt: daysAgo(5),
    lastUpdated: hoursAgo(6),
    version: 1,
    fileSize: "2.1 MB",
    pageCount: 18,
    tags: ["Auto-renewal", "Payments"],
    clauses: saasClauses,
    documentSections: saasDocumentSections,
  },
  {
    id: "ctr_003",
    title: "NDA — Project Garuda",
    counterparty: "Infosys BPM Ltd",
    contractType: "nda",
    jurisdiction: "Pune",
    governingLaw: "Laws of India",
    status: "approved",
    riskSummary: {
      high: 0,
      medium: 1,
      low: 5,
      standard: 6,
      missing: 0,
      overallScore: 92,
      escalationRecommended: false,
    },
    totalClauses: 12,
    reviewedClauses: 12,
    assignedTo: "Ravi Shankar",
    uploadedBy: "Karan Malhotra",
    uploadedAt: daysAgo(8),
    lastUpdated: hoursAgo(28),
    version: 3,
    fileSize: "1.2 MB",
    pageCount: 6,
    tags: ["NDA", "M&A"],
    clauses: ndaClauses,
  },
  {
    id: "ctr_004",
    title: "Employment Agreement — Senior Counsel",
    counterparty: "Internal HR",
    contractType: "employment",
    jurisdiction: "Delhi NCT",
    governingLaw: "Laws of India",
    status: "pending",
    riskSummary: {
      high: 0,
      medium: 0,
      low: 0,
      standard: 0,
      missing: 0,
      overallScore: 0,
      escalationRecommended: false,
    },
    totalClauses: 18,
    reviewedClauses: 0,
    uploadedBy: "Divya Iyer",
    uploadedAt: hoursAgo(4),
    lastUpdated: hoursAgo(4),
    version: 1,
    fileSize: "1.8 MB",
    pageCount: 14,
    tags: ["ESOP", "Non-compete"],
  },
  {
    id: "ctr_005",
    title: "Cloud Infrastructure Agreement",
    counterparty: "AWS India Pvt Ltd",
    contractType: "vendor_agreement",
    jurisdiction: "Mumbai",
    governingLaw: "Laws of India",
    status: "in_progress",
    riskSummary: {
      high: 3,
      medium: 4,
      low: 6,
      standard: 10,
      missing: 1,
      overallScore: 58,
      escalationRecommended: true,
      escalationReason: "Cross-border data transfer terms under review",
    },
    totalClauses: 28,
    reviewedClauses: 17,
    assignedTo: "Arjun Subramanian",
    uploadedBy: "Priya Menon",
    uploadedAt: hoursAgo(5),
    lastUpdated: hoursAgo(1),
    version: 1,
    fileSize: "8.5 MB",
    pageCount: 42,
    tags: ["Cross-border", "DPDP", "Cloud"],
    clauses: cloudClauses,
  },
  {
    id: "ctr_006",
    title: "Consulting Services Agreement",
    counterparty: "Deloitte Touche Tohmatsu India LLP",
    contractType: "consulting",
    jurisdiction: "Gurugram",
    governingLaw: "Laws of India",
    status: "reviewed",
    riskSummary: {
      high: 1,
      medium: 3,
      low: 6,
      standard: 9,
      missing: 0,
      overallScore: 76,
      escalationRecommended: false,
    },
    totalClauses: 19,
    reviewedClauses: 19,
    assignedTo: "Karan Malhotra",
    uploadedBy: "Nidhi Kapoor",
    uploadedAt: daysAgo(12),
    lastUpdated: hoursAgo(40),
    version: 2,
    fileSize: "3.2 MB",
    pageCount: 22,
    tags: ["Consulting", "IP"],
    clauses: consultingClauses,
  },
  {
    id: "ctr_007",
    title: "Data Processing Agreement",
    counterparty: "Freshworks Inc",
    contractType: "vendor_agreement",
    jurisdiction: "Chennai",
    governingLaw: "Laws of India",
    status: "needs_attention",
    riskSummary: {
      high: 5,
      medium: 6,
      low: 2,
      standard: 2,
      missing: 0,
      overallScore: 41,
      escalationRecommended: true,
      escalationReason: "Multiple DPDP gaps; recommend external counsel review",
    },
    totalClauses: 24,
    reviewedClauses: 24,
    assignedTo: "Priya Menon",
    uploadedBy: "Ravi Shankar",
    uploadedAt: daysAgo(2),
    lastUpdated: hoursAgo(8),
    version: 1,
    fileSize: "2.9 MB",
    pageCount: 19,
    tags: ["DPDP", "Cross-border", "DPA"],
    clauses: dpaClauses,
  },
  {
    id: "ctr_008",
    title: "Partnership Agreement — FinTech Alliance",
    counterparty: "PhonePe Pvt Ltd",
    contractType: "partnership",
    jurisdiction: "Bengaluru",
    governingLaw: "Laws of India",
    status: "sent_back",
    riskSummary: {
      high: 1,
      medium: 2,
      low: 5,
      standard: 6,
      missing: 0,
      overallScore: 78,
      escalationRecommended: false,
    },
    totalClauses: 26,
    reviewedClauses: 26,
    assignedTo: "Divya Iyer",
    uploadedBy: "Priya Menon",
    uploadedAt: daysAgo(15),
    lastUpdated: hoursAgo(48),
    version: 4,
    fileSize: "5.4 MB",
    pageCount: 28,
    tags: ["FinTech", "Partnership", "RBI"],
    clauses: partnershipClauses,
  },
];

export const dashboardMetrics: DashboardMetrics = {
  contractsInReview: { value: 23, trend: 12, trendDirection: "up" },
  avgReviewTime: { value: 18, unit: "min", trend: 64, trendDirection: "down" },
  riskFlagsResolved: { value: 142, period: "this month" },
  playbookAdherence: { value: 94, unit: "%" },
};

export const activityFeed: ActivityItem[] = [
  {
    id: "act_001",
    user: teamMembers.priya,
    action: "approved redlines on",
    target: "Vendor MSA — Acme Cloud",
    timestamp: hoursAgo(2),
    type: "approve",
  },
  {
    id: "act_002",
    user: teamMembers.arjun,
    action: "uploaded",
    target: "Cloud Infrastructure Agreement",
    timestamp: hoursAgo(5),
    type: "upload",
  },
  {
    id: "act_003",
    user: teamMembers.nidhi,
    action: "commented on §14.2 of",
    target: "SaaS Subscription Agreement",
    timestamp: hoursAgo(8),
    type: "comment",
  },
  {
    id: "act_004",
    user: teamMembers.ravi,
    action: "assigned",
    target: "DPA — Freshworks",
    timestamp: hoursAgo(26),
    type: "assign",
  },
  {
    id: "act_005",
    user: teamMembers.divya,
    action: "completed review of",
    target: "Partnership Agreement — PhonePe",
    timestamp: hoursAgo(48),
    type: "review",
  },
  {
    id: "act_006",
    user: teamMembers.karan,
    action: "uploaded v2 of",
    target: "Consulting Services — Deloitte",
    timestamp: daysAgo(2),
    type: "upload",
  },
  {
    id: "act_007",
    user: teamMembers.priya,
    action: "flagged §8.3 in",
    target: "Cloud Infrastructure Agreement",
    timestamp: daysAgo(2),
    type: "comment",
  },
  {
    id: "act_008",
    user: teamMembers.arjun,
    action: "approved",
    target: "NDA — Project Garuda",
    timestamp: daysAgo(3),
    type: "approve",
  },
];

export const topFlaggedClauses: TopClauseFlag[] = [
  { category: "indemnification", label: "Indemnification", count: 34, trend: "up" },
  { category: "limitation_of_liability", label: "Limitation of Liability", count: 28, trend: "stable" },
  { category: "termination", label: "Term & Termination", count: 19, trend: "down" },
  { category: "data_protection_dpdp", label: "Data Protection / DPDP", count: 17, trend: "up" },
  { category: "ip_assignment", label: "IP Assignment", count: 12, trend: "stable" },
];

export const riskDistribution = [
  { name: "High", value: 16, color: "#e5484d" },
  { name: "Medium", value: 28, color: "#f2a93b" },
  { name: "Standard", value: 47, color: "#3dd68c" },
  { name: "Missing", value: 4, color: "#4cc2ff" },
];

// Tiny sparkline data for KPI cards (12 data points each)
export const sparklines = {
  contractsInReview: [12, 14, 13, 16, 15, 18, 17, 19, 20, 19, 22, 23],
  avgReviewTime: [50, 45, 42, 38, 36, 32, 28, 26, 24, 22, 20, 18],
  riskFlagsResolved: [80, 95, 110, 100, 115, 120, 125, 130, 132, 138, 140, 142],
};
