// Project rule: never use the phrase "legal advice" — always "legal information".
// All exported artifacts carry this disclaimer to stay DPDP Act 2023 aware.

export const DISCLAIMER_SHORT =
  "This report contains legal information and analysis generated by AI. It is not a substitute for review by qualified counsel.";

export const DISCLAIMER_LONG =
  "This document contains legal information and analysis generated by AI based on the contract supplied. It is not a substitute for review by qualified counsel and does not constitute solicitor-client communication. Citations are drawn from Indian statutes including the Indian Contract Act, 1872 and the Digital Personal Data Protection Act, 2023; reviewers should verify each citation against the latest published source before relying on it.";

export const COMMENT_AUTHOR_INITIALS = "AI";
